### ISSUE TITLE
Implement Main Register Page

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-anc#1]
<img width="408" alt="screen shot 2018-07-06 at 10 07 54 am" src="https://user-images.githubusercontent.com/3488986/42364642-8323896a-8104-11e8-839d-316f8d0b6e76.png">

This will be the landing page after the user has completed the logging in workflow (TBD): 
- [x] The top left circle widget has the logged in user's initials
- [x] Tapping on the user's initials opens the [side menu](https://github.com/OpenSRP/opensrp-client-anc/issues/14). Swiping from the left also opens the side menu.
- [x] The facility name dropdown should consist of the location hierarchy (the logged in user's assigned location should be shown and selected as the default each time they log in to the application)
- [x] The ADD button in the top right corner should open a new ANC Registration form
- [x] Fts search by first name, last name or ID (`first_name`, `last_name`, `anc_id` from the ANC reg form)
- [ ] Advanced search icon launches the [advanced search page](https://github.com/OpenSRP/opensrp-client-anc/issues/15)
- [x] Search by QR code (contains the `anc_id`)
- [ ] Sort and filter row
- Number of clients currently displayed in the register list (this number changes based on filter(s) selected)
- In parentheses, show the current sort selection
- Filter shows how many filters are selected (if 0 filters are selected, do not show the parentheses), tapping opens the [filter menu](https://github.com/OpenSRP/opensrp-client-anc/issues/13)
- [x] Display demographic information (`first_name`, `last_name`, `age`, `gest_age`, `anc_id`). Everything except gest_age is from the ANC Reg form. Gest_age is from the 1st contact visit, so for women who are registered but without any contact visits recorded, GA will be empty.
- [ ] "Attention flag" widget displays the number of issues/concerns the woman has (https://github.com/OpenSRP/opensrp-client-anc/issues/24)
- [ ] Due buttons:
- Contact # [date] - blue = contact due 
- Contact # [date] - red = contact overdue
- Contact # [date] - white (not shown) = contact upcoming
- Contact # in progress - orange = contact started and saved but not submitted
- Contact # done today = A contact was submitted today. The button resets to the next due contact the next day
- Due Delivery - blue = Woman is due to deliver (tapping opens https://github.com/OpenSRP/opensrp-client-anc/issues/20)
- Due Delivery - red (not shown) = Woman is overdue to deliver (tapping opens https://github.com/OpenSRP/opensrp-client-anc/issues/20)
- [x] Pagination
- [x] Unit Tests

**Comment by cagulas** [comment]
@keymane @ndegwamartin Please note the updated mockup above. The registration form button has been changed from a plus button to "ADD" button.

@rowo Please flag to me any future changes you make to mockups in Marvel that are already posted on Github. I luckily caught this change.

**Comment by cagulas** [comment]
@rowo Can you also respond to this feedback from earlier and see if these are changes you'd like to make: 

"On the above mockup, couldn't we make the entire row where it says 403 clients tappable (i.e. one button) where it opens the sort/filter widget? Instead of separating into the two sections? so it would appear as if it's just a single button, and it would show the sort selection and number of filters selected. And in the search bar row, couldn't we minimize that blank space between the search window and the advanced search button a bit?"

**Comment by cagulas** [comment]
@rowo Can you reply to the above comment?

**Comment by rowo** [comment]
@keymane @cagulas 
- "entire row tappable" - sure that's possible. I am a bit concerned about the amount of tappable stuff though — the way I had originally done the filter bar was without the (Sort: updated) portion which gave it some breathing room — a pause in content before the deluge of clients. Then the sort text was added, filling that space. So if the entire bar becomes a button it'll be buttons on top of buttons and every space filled with text. I guess there's no way around it.
- "search bar row blank space" - yeah that's fine. Or alternatively, you can space them out evenly and move the search button to the right so it's not confused with the search bar.
- since we're adding the ["what do you want to do"  step on app opening](https://marvelapp.com/project/2823817/screen/45108976/comments/), I almost want to move the advanced search and add new buttons into a three dot top right dropdown to reduce the noise. Thoughts? is it too late?

**Comment by keymane** [comment]
@rowo @cagulas I agree, making the entire row clickable may be a bit confusing. We could separate filter and sort functionality and have a button and label for each or update the right button in a way that notifies the user that they'll be changing **filter** and/or **sort** parameters

Separating the search button (advanced search) and the search bar is a good idea and since we are targeting smart phone devices, we could probably move some of the buttons to the menu dropdown

**Comment by rowo** [comment]
In some mobile apps, "Sort" is normally not used very much and is nested within the Filter menu in for that reason — and it doesn't seem super confusing to me. I can see how OpenSRP might be different from say a Yelp or Amazon or maps apps though.

If we had to choose between a "Filter" text button vs. a filter+sort icon, I'd rather just use the "Filter" text I think to avoid having three small icons huddled together over there. 

Also, I don't think the sort notification is necessary unless it changes from default i.e. recently updated.

**Comment by cagulas** [comment]
@rowo ok sure, this makes sense, thanks for explaining.

**Comment by rowo** [comment]
@keymane @cagulas @ndegwamartin hi just wanted to let you know there's an updated screen for the list here: https://marvelapp.com/project/2823817/screen/46862443

![new-list-02](https://user-images.githubusercontent.com/1584163/44321175-712ee500-a414-11e8-8d52-743dc693f61c.png)

**Comment by cagulas** [comment]
@rowo Lgtm. For the orange "in-progress" button, would that be the full button orange or only the outline as well?

**Comment by cagulas** [comment]
@ndegwamartin Since quite a few things have changed, I'm going to close this issue and create a new one with the updated main register page.

**Comment by cagulas** [comment]
https://github.com/OpenSRP/opensrp-client-anc/issues/56
