### ISSUE TITLE
Implement top section of profile page and minimize on scroll

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#26]
<img width="313" alt="screen shot 2018-07-06 at 12 59 39 pm" src="https://user-images.githubusercontent.com/3488986/42373045-78d6086c-811c-11e8-9e9d-f36e144269e7.png">

Everything with a blue background in the above mockup is ready to be developed. The content below is still unfinished, so work on the top blue section only in the meantime.

- [x] Back arrow takes you back to the main register page 
- [x] Three dots in upper right corner opens an [edit menu](https://github.com/OpenSRP/opensrp-client-anc/issues/27)
- [x] Woman's image or [avatar](https://github.com/OpenSRP/opensrp-client-anc/issues/25) if no picture taken (`wom_image` from ANC Reg)
- [x] `first_name` `last_name` from ANC Reg
- [x] ID: `anc_id` (from ANC Reg)
- [x] AGE `age` (from ANC Reg)
- [x] GA: `gest_age` WEEKS (from 1st contact)
- [x] OVERVIEW, CONTACTS, TASKS tabs
- [x] Can tap on tab or swipe left and right to switch tabs
- [x] If woman is registered and no contact is done yet, leave GA blank
- [x] Registration info button opens the filled in registration form for the woman, where [she can view or edit](https://github.com/OpenSRP/opensrp-client-anc/issues/28)
- [x] On scroll, the top section minimizes, and the top bar shows the woman's name (see below)
- [x] Unit testing

<img width="337" alt="screen shot 2018-07-06 at 1 07 46 pm" src="https://user-images.githubusercontent.com/3488986/42373455-9b7962d2-811d-11e8-8eeb-dd02130b81d7.png">

**Comment by cagulas** [comment]
This looks really great. Do you think we can improve this a bit more so that the name and avatar image that is centered disappears faster when you scroll down? Right now, there is like a half second where you see the names overlapping.

@rowo Pls review when you get a chance. Martin shared the apk and login in the opensrp channel (also pinned).

**Comment by ndegwamartin** [comment]
@cagulas yeah we can do this, it does that because of the animation which we can remove

**Comment by cagulas** [comment]
This looks great.

**Comment by cagulas** [comment]
QA 11th Oct build:

The issue with the animation seems to have reverted. Can we fix this again?

**Comment by cagulas** [comment]
This is done. Closing.
