### ISSUE TITLE
Fix the Expansion panel functional QA 

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-anc#262]
- [x] The undo functionality should be implemented as suggested here https://github.com/OpenSRP/opensrp-client-anc/issues/72

- [x] The saving of the values should be implemented as suggested here https://github.com/OpenSRP/opensrp-client-anc/issues/59

- [x] Ordering the selected test results according to the questions arrangement on the popup

- [x] Update the Expansion panel to fit the requirements on issue #256 

- [x] Add more room between the expansion panel rows issue #255 

 
![device-2019-04-05-113117](https://user-images.githubusercontent.com/4817531/55626934-8d21a400-57b5-11e9-95d0-17e750b01ea4.png)

![device-2019-04-05-151530](https://user-images.githubusercontent.com/4817531/55626987-ba6e5200-57b5-11e9-8a7a-14fdbbcb50f6.png)

![device-2019-04-10-170354](https://user-images.githubusercontent.com/4817531/55885484-b45fe300-5bb2-11e9-9603-d6d39249c4b4.png)

**Comment by cagulas** [comment]
lgtm
