### ISSUE TITLE
Implement contact workflow

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#39]
This is the epic for the entire contact workflow. Each component below will have a separate issue created for it.

- [x] Quick Check (#40)
- [x] Contact page with containers (#42)
- [x] Contact save widget (#43)
- [ ] View ANC History (#95)
- [x] Profile (#48)
- [x] Symptoms & Follow-up (#52)
- [x] Physical Exam (#74)
- [x] Tests (#53)
- [x] Counseling & Treatment (#75)
- [x] Contact summary (#76)
- [x] Contact recorded (#77)

**Comment by cagulas** [comment]
Closing this. All but ANC History is done, which will be worked on later.
