### ISSUE TITLE
Implement new main register page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#56]
<img src="https://user-images.githubusercontent.com/1584163/44397808-9b190200-a50f-11e8-9496-65429aaca076.png" width="480">

- [x] The main register page shows the list of all ANC clients for that health facility. The user lands on this page after logging in. If it's the first time login for any user from that health facility, the user lands on this page after the site characteristics configuration walkthrough (https://github.com/OpenSRP/opensrp-client-anc/issues/18).
- [x] The user can return to this page whenever they tap the "Clients" button in the bottom choices menu.
- [x] QR scan button in top left (https://github.com/OpenSRP/opensrp-client-anc/issues/44) contains the `anc_id`
- [x] OpenSRP logo in top center
- [x] Sync button in top right forces a sync in between automatic attempts. Toaster message on bottom gives sync result.
- [x] Find name or ID is the Fts search by first name, last name or ID (`first_name`, `last_name`, `anc_id` from the ANC reg form)
- [x] Filter button opens the sort/filter menu (https://github.com/OpenSRP/opensrp-client-anc/issues/13)
- [x] 403 clients row is non-tappable. It shows the count of clients currently displayed in the list and also sort/filters applied (apart from the default sort of last updated and default no filters applied). When sort or filters are applied besides the default, format would be: `31 clients (Last name, Has tasks due, HIV pos...)`
- [x] Display demographic information (`first_name`, `last_name`, `age`, `gest_age`, `anc_id`). Everything except `gest_age` is from the ANC Reg form. `Gest_age` is from the 1st contact visit, so for women who are registered but without any contact visits recorded, GA will be empty (and hide the "GA:" label).
- [x] "Attention flag" widget displays the number of issues/concerns the woman has (#24) — if none, then it doesn't appear.
- [x] Contact buttons:
Contact # [date] - blue outline = contact due
Contact # [date] - red = contact overdue
Contact # [date] - white (Elly Smith) = contact upcoming but not due. Button is still active to go to contact form.
Contact # [date] - orange (Charity) = contact started and saved but not submitted
Contact # done today [green check] = (not shown) A contact was submitted today. The button resets to the next due contact the next day (i.e. turns into the white button like Elly Smith)
Due Delivery - blue outline = Woman is due to deliver (tapping opens #20)
Due Delivery - red (not shown) = Woman is overdue to deliver (tapping opens #20)
- [x] Search in bottom choices bar opens advanced search (https://github.com/OpenSRP/opensrp-client-anc/issues/15) as full screen dialog
- [x] Register in bottom choices bar opens reg form (https://github.com/OpenSRP/opensrp-client-anc/issues/2) as full screen dialog
- [x] Library in bottom choices bar opens library placeholder page (https://github.com/OpenSRP/opensrp-client-anc/issues/57). Bottom nav remains at top level of library content.
- [x] Me in bottom choices bar opens Me profile page (https://github.com/OpenSRP/opensrp-client-anc/issues/58). Bottom nav remains at top level of "Me" content.
- [x] Pagination
- [x] Unit Tests

**Comment by rowo** [comment]
Shared these icons via slack already with Benjamin. The current library and search icons (as of Aug 27) are okay.

![icon-nav-new-](https://user-images.githubusercontent.com/1584163/44680363-8951c600-aa0b-11e8-8413-5da55d18e376.png)
![icon-nav-new-focus](https://user-images.githubusercontent.com/1584163/44680364-8951c600-aa0b-11e8-9bcc-8067688d4c71.png)
![icon-nav-clients](https://user-images.githubusercontent.com/1584163/44680365-8951c600-aa0b-11e8-846b-68333aa5d1f5.png)
![icon-nav-clients-focus](https://user-images.githubusercontent.com/1584163/44680366-8951c600-aa0b-11e8-8030-34ca9754cdfc.png)

In focus icons should be #208cc5

**Comment by cagulas** [comment]
QA 18th Oct build:

- [ ] When you do a search in the search bar, "XX clients" reverts to "XX Client". It should be "clients" always.
- [ ] Replace OpenSRP logo, it's blurry.
- [ ] The attention flag icon should be anchored to the right contact button.
- [ ] I actually think the top right sync icon looks a little pixelated as well. Can we check on that?

**Comment by cagulas** [comment]
Closing. This issue is complete.
