### ISSUE TITLE
Implement Library placeholder page

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#57]
- [x] The Library placeholder page opens when the user taps "Library" in the bottom choices menu in the main register page (https://github.com/OpenSRP/opensrp-client-anc/issues/56).
- [x] It will look similar to Pop Charact page (https://github.com/OpenSRP/opensrp-client-anc/issues/22) in that top left X exits back to main register page. Title will be "Library" and the page will be blank with a note saying "Library content".

We will eventually replace this with the counseling pdf content that we'll be getting from WHO later on in the project.

**Comment by cagulas** [comment]
@ndegwamartin Think this can go to QA, no?

**Comment by cagulas** [comment]
QA on 14th Dec 2018:

- [ ] It will look similar to Pop Charact page (#22) in that top left X exits back to main register page. Title will be "Library". @ndegwamartin See pop charact. page. It should be implemented like that full screen dialog with a top left X to exit out. Right now, it keeps the top blue OpenSRP header bar, which is awkward, because the qr code and the sync buttons are not active, so it's there for no reason.

**Comment by faith-mutua** [comment]
QA on 201th Dec 2018: 

- [ ] The top left X for exiting the page is missing.

- [ ] The title "Library" is also missing.

**Comment by cagulas** [comment]
Lgtm
