### ISSUE TITLE
Implement "Me" page from bottom choices menu

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-anc#58]
![me](https://user-images.githubusercontent.com/3488986/44333165-b683fe80-a476-11e8-89fa-9df54a4a8bb1.png)

- [x] Me profile page opens when you tap on the Me button in bottom choices menu
- [x] Note - the bottom choices menu in above mockup is not correct - please use bottom choices menu from main register page issue instead (https://github.com/OpenSRP/opensrp-client-anc/issues/56)
- [x] User's initials and first and last name
- [x] Location shows user's current location selected, opens a service location widget for user to change locations if needed. The location should default to the user's home facility location and default back to this with each app login.
- [x] Pop characteristics opens the pop charact page (https://github.com/OpenSRP/opensrp-client-anc/issues/22)
- [x] Site characteristics opens the site charact page (https://github.com/OpenSRP/opensrp-client-anc/issues/21)
- [x] Remove Settings for now. In future, this could hold a language dropdown, but not needed for now.
- [x] Log out button

**Comment by cagulas** [comment]
@rowo Can you please comment on whether we can show last sync date and time here, refer to my comment in Marvel, https://marvelapp.com/project/2823817/canvas/46121628/.

**Comment by cagulas** [comment]
@rowo cool, in terms of placement, would that be top right? Should we have another sync button as well?

**Comment by cagulas** [comment]
QA 11th October build:

- [ ] Can we get rid of the top blue OpenSRP/QR code/Sync button bar? In the mockups, the Me profile page takes up the entire screen.
- [ ] Location is blank
- [ ] What is the Contact Summary? This shouldn't be here.
- [ ] No need to capitalize "Characteristics" for Pop or Site. 
- [ ] Space needed in Log out
- [ ] Synced doesn't need to be capitalized
- [ ] Version doesn't need to be capitalized
- [ ] I think we can abbreviate the months, i.e. built on 11 Oct 2018
- [ ] Once top blue bar and contact summary row are removed, we can add space between the log out button and the data synced/app version lines
- [ ] The Me icon in the bottom navigation bar should be as per mockups. Was this a native Android library constraint? If so, I'm sure it's fine the way it is.
- [ ] App crashes when you hit Location row (is this because OpenMRS hasn't been set up with the locations yet?)

**Comment by cagulas** [comment]
QA 16th Oct build:

- [ ] This is looking great. The only remaining thing is that the location name seems very faint and slightly uneven with the "Location" text. See mockups above where it says Linda clinic. It should be the same font as the Location text.

**Comment by cagulas** [comment]
QA 18th Oct build;

Lgtm!
