### ISSUE TITLE
Development of OptiBP widget

### ISSUE THREAD

**Issue by muchuri** [opensrp/opensrp-client-anc#603]
Development of an android widget that will invoke OptiBP app from WHO ANC app

**Comment by dubdabasoduba** [comment]
**New widget details**
- This widget should be built on native forms
- [ ] This widget should follow the following [JSON specification](https://github.com/OpenSRP/opensrp-client-native-form/issues/570)
- [ ] This widget should account for multi-language support.

**How the widget should work**
- [ ] Initiate the launch of the OptiBp application via an Android Intent. Documentation on how to launch the app using an intent can be found [here](https://github.com/opensrp/opensrp-client-anc/issues/602)
- [ ] Pass the following client information to the OptiBp application using JSON. This [issue](https://github.com/OpenSRP/opensrp-client-anc/issues/599) shows how this JSON should be formatted
    - Client Id (BaseEntityId)
    - OpenSRP ID
- [ ] This widget should also receive the [FHIR diagnostic report](https://www.hl7.org/fhir/diagnosticreport.html) sent from the OptiBp mobile application. Here is a [sample report](https://github.com/OpenSRP/opensrp-client-anc/issues/601) from optibp
    - After receiving the report then, the widget would break down the report and get the diastolic and systolic values. 
    - These values should then be assigned to the respective fields on the WHO ANC application.
    - The fields to be used will be defined as part of the widget. These are described in the widget [JSON specification](https://github.com/OpenSRP/opensrp-client-native-form/issues/570) on the `fields_to_use_value` attribute. 
- [ ] This widget should also show appropriate error messages in case something goes wrong in the following areas.
    - Data transfers to and from the OptiBp mobile application. 
    - Diagnostic report data breakdown
    - Values assignment 
    - In case the OptiBp mobile application is missing we should show the user an error message and suggest the installing of the OptiBp mobile application. 
   - In case the mobile application can’t be installed then we let the user enter the diastolic & systolic values manually.
